import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header'
import MainSection from '../components/main'
import styles from '../styles/Home.module.css'
import utilStyles from '../styles/utils.module.css';

export default function Home() {
  return (
    <div className='bg-[#0D0D0D]'>
      <Head>
        <title>FRONTIERX</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <header>
        <Header />
      </header>

      <main className={`overflow-hidden w-[100vw] ${utilStyles.mainBg}`}>
        <MainSection />
      </main>

      <footer className='h-[12.81rem] flex items-center justify-center'>
        <img src='/logoFooter.svg' />
      </footer>
    </div>
  )
}
