import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header'
import MainSection from '../components/main'
import styles from '../styles/Home.module.css'
import utilStyles from '../styles/utils.module.css';

export default function Home() {
  return (
    <div className='bg-[#0D0D0D]'>
      <Head>
        <title>FRONTIERX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet"></link>
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <header>
        <Header />
      </header>

      <main className={`overflow-hidden w-[100vw] ${utilStyles.mainBg}`}>
        <MainSection />
      </main>

      <footer className='h-[12.81rem] flex items-center justify-center'>
        <img src='/logoFooter.svg' />
      </footer>
    </div>
  )
}
